### ISSUE TITLE
Generation should fail when added to non-partial class

### ISSUE THREAD

**Issue by jvmlet** [beakona/AutoAs#1]
The current behaviour does nothing when the attribute is added to non-partial class. 
Please fail the compilation in this case.

**Comment by beakona** [comment]
That case should be handled. Is there any other text in build output?
Here is code I tested using nuget AutoAs 1.0.0 added in empty project.

```cs
internal class Program
{
    static void Main()
    {
        var t = new TestClass();
    }
}

[GenerateAutoAs]
public class TestClass
{
}
```

Here are messages I get:

- BKAA01	- Type 'ConsoleApp1.TestClass' is not marked as partial. (https://github.com/beakona/AutoAs)
- IDE0059 - Unnecessary assignment of a value to 't'

**Comment by jvmlet** [comment]
Make `TestCass` to implement some interface

**Comment by beakona** [comment]
I've tried and got same errors (BKAA01, IDE0059).

After detecting a named type with GenerateAutoAsAttribute, source generator makes 3 tests:
- `IsPartial()`
- `!IsStatic`
- `type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct`

If compiler does not generate error mesage, we have following cases:
1. source generator did not enter this branch at all - I've made poor choice because I did not rename attribute and now there are two classes `BeaKona.GenerateAutoAsAttribute`, one comes from `AutoInterface` and one from `AutoAs`. Clearing solution could solve the problem.
2. IsPartial() have a bug. This is my method that takes modifiers of type declaration and search for SyntaxToken.IsKind(SyntaxKind.PartialKeyword) and so far it works for AutoInterface without known issues.
3. something else?
